// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdJovt8FKMu3KXoz0CUsGhT3S2JKzTA4A',
    appId: '1:510387520974:web:267fd0348769fb3b8fd79f',
    messagingSenderId: '510387520974',
    projectId: 'irvine-sixguys',
    authDomain: 'irvine-sixguys.firebaseapp.com',
    storageBucket: 'irvine-sixguys.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKh9vEleR4uBvufPnZy_9noCBd1HFl5Vk',
    appId: '1:510387520974:android:6942d664d4a526208fd79f',
    messagingSenderId: '510387520974',
    projectId: 'irvine-sixguys',
    storageBucket: 'irvine-sixguys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNuqw8t4W68pFgRAmR4yy24b4Qou1U9AU',
    appId: '1:510387520974:ios:f9e1f091a73c215c8fd79f',
    messagingSenderId: '510387520974',
    projectId: 'irvine-sixguys',
    storageBucket: 'irvine-sixguys.appspot.com',
    iosBundleId: 'com.irvine-tech-hub.sixguys',
  );
}
